# Clojure CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-ubuntu/ for more details
#
version: 2.1

executors:
  ubuntu:
    machine:
      image: ubuntu-1604:202004-01
    working_directory: ~/repo

jobs:
  build:
    executor: ubuntu

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Install Leiningen
          command: wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && chmod a+x lein && ./lein

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      # run tests!
      - run: lein bat-test cloverage

      - store_test_results:
          path: target

  style:
    executor: ubuntu

    steps:
      - checkout
      - run:
          name: Install cljstyle
          environment:
            CLJSTYLE_VERSION: 0.13.0
          command: |
            wget https://github.com/greglook/cljstyle/releases/download/${CLJSTYLE_VERSION}/cljstyle_${CLJSTYLE_VERSION}_linux.tar.gz
            tar -xzf cljstyle_${CLJSTYLE_VERSION}_linux.tar.gz
      - run:
          name: Check style
          command: "./cljstyle check --report"
